# Generated by Django 5.0.6 on 2024-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='maintenancetechnician',
            name='certification',
        ),
        migrations.AddField(
            model_name='contact',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
